export type AudioEffectSettings = { enabled: boolean; highPass: number; lowPass: number; eqLow: number; eqMid: number; eqHigh: number; compressor: number; gate: number; deEsser: number; reverb: number; delay: number; limiter: boolean }
export const defaultAudioEffects = (): AudioEffectSettings => ({ enabled: false, highPass: 20, lowPass: 20000, eqLow: 0, eqMid: 0, eqHigh: 0, compressor: 0, gate: -80, deEsser: 0, reverb: 0, delay: 0, limiter: false })
export const effectPresets: Record<string, Partial<AudioEffectSettings>> = {
  clean: { enabled: true, highPass: 70, lowPass: 18000, compressor: 35, gate: -55, deEsser: 25, limiter: true },
  vocal: { enabled: true, highPass: 95, eqLow: -2, eqMid: 2.5, eqHigh: 2, compressor: 45, gate: -50, deEsser: 38, reverb: 9, limiter: true },
  podcast: { enabled: true, highPass: 80, lowPass: 15500, eqLow: 1.5, eqMid: 2, eqHigh: -1, compressor: 55, gate: -48, deEsser: 28, limiter: true },
  music: { enabled: true, highPass: 30, lowPass: 19500, compressor: 20, reverb: 6, limiter: true },
}
const filter = (context: BaseAudioContext, type: BiquadFilterType, frequency: number, gain = 0, q = .7) => { const node = context.createBiquadFilter(); node.type = type; node.frequency.value = frequency; node.gain.value = gain; node.Q.value = q; return node }
export function connectAudioEffects(context: BaseAudioContext, source: AudioNode, destination: AudioNode, settings?: AudioEffectSettings) {
  if (!settings?.enabled) { source.connect(destination); return }
  let tail = source; const append = (node: AudioNode) => { tail.connect(node); tail = node }
  if (settings.highPass > 20) append(filter(context, 'highpass', settings.highPass)); if (settings.lowPass < 20000) append(filter(context, 'lowpass', settings.lowPass)); if (settings.eqLow) append(filter(context, 'lowshelf', 180, settings.eqLow)); if (settings.eqMid) append(filter(context, 'peaking', 1400, settings.eqMid, 1)); if (settings.eqHigh) append(filter(context, 'highshelf', 6500, settings.eqHigh)); if (settings.deEsser > 0) append(filter(context, 'peaking', 6800, -settings.deEsser * .18, 2.4))
  if (settings.gate > -79) { const gate = context.createWaveShaper(), threshold = 10 ** (settings.gate / 20), curve = new Float32Array(4096); for (let index = 0; index < curve.length; index++) { const value = index / (curve.length - 1) * 2 - 1; curve[index] = Math.abs(value) < threshold ? 0 : value } gate.curve = curve; gate.oversample = '2x'; append(gate) }
  if (settings.compressor > 0) { const compressor = context.createDynamicsCompressor(); compressor.threshold.value = -8 - settings.compressor * .22; compressor.knee.value = 18; compressor.ratio.value = 1 + settings.compressor * .09; compressor.attack.value = .006; compressor.release.value = .16; append(compressor) }
  if (settings.reverb > 0) { const convolver = context.createConvolver(), sampleRate = context.sampleRate, impulse = context.createBuffer(2, Math.floor(sampleRate * 1.6), sampleRate); for (let channel = 0; channel < 2; channel++) { const data = impulse.getChannelData(channel); for (let index = 0; index < data.length; index++) data[index] = (Math.random() * 2 - 1) * (1 - index / data.length) ** 2.4 } convolver.buffer = impulse; const dry = context.createGain(), wet = context.createGain(), mix = context.createGain(); wet.gain.value = Math.min(.65, settings.reverb / 100 * .65); tail.connect(dry).connect(mix); tail.connect(convolver).connect(wet).connect(mix); tail = mix }
  if (settings.delay > 0) { const delay = context.createDelay(1), feedback = context.createGain(), wet = context.createGain(), mix = context.createGain(), dry = context.createGain(); delay.delayTime.value = .24; feedback.gain.value = Math.min(.55, settings.delay / 100 * .55); wet.gain.value = Math.min(.55, settings.delay / 100 * .55); tail.connect(dry).connect(mix); tail.connect(delay); delay.connect(feedback).connect(delay); delay.connect(wet).connect(mix); tail = mix }
  if (settings.limiter) { const limiter = context.createDynamicsCompressor(); limiter.threshold.value = -1; limiter.knee.value = 0; limiter.ratio.value = 20; limiter.attack.value = .002; limiter.release.value = .1; append(limiter) } tail.connect(destination)
}
