import { Power, RotateCcw } from 'lucide-react'
import { defaultAudioEffects, effectPresets, type AudioEffectSettings } from './audio-effects'
import PreciseRange from './PreciseRange'

type Props = { settings: AudioEffectSettings; scope: 'clip' | 'track'; clipAvailable: boolean; onScope: (scope: 'clip' | 'track') => void; onChange: (settings: AudioEffectSettings) => void }
const Control = ({ label, min, max, step, value, unit, change }: { label: string; min: number; max: number; step: number; value: number; unit: string; change: (value: number) => void }) => <label>{label}<output>{value.toFixed(step < 1 ? 1 : 0)}{unit}</output><PreciseRange ariaLabel={label} min={min} max={max} step={step} value={value} onChange={change}/></label>

export default function AudioEffectsPanel({ settings, scope, clipAvailable, onScope, onChange }: Props) {
  const patch = (value: Partial<AudioEffectSettings>) => onChange({ ...settings, ...value })
  return <section className="audio-effects-panel"><div className="effects-heading"><strong>标准音频效果</strong><button className={settings.enabled ? 'active' : ''} onClick={() => patch({ enabled: !settings.enabled })}><Power/>{settings.enabled ? '效果开启' : '全部旁路'}</button></div><div className="effects-scope"><button disabled={!clipAvailable} className={scope === 'clip' ? 'active' : ''} onClick={() => onScope('clip')}>当前片段</button><button className={scope === 'track' ? 'active' : ''} onClick={() => onScope('track')}>整条音轨</button></div><div className="effect-presets"><button onClick={() => patch(effectPresets.clean)}>清晰</button><button onClick={() => patch(effectPresets.vocal)}>人声</button><button onClick={() => patch(effectPresets.podcast)}>播客</button><button onClick={() => patch(effectPresets.music)}>音乐</button></div><div className={!settings.enabled ? 'effects-disabled' : ''}><Control label="高通滤波" min={20} max={500} step={5} value={settings.highPass} unit="Hz" change={highPass => patch({ highPass })}/><Control label="低通滤波" min={2000} max={20000} step={100} value={settings.lowPass} unit="Hz" change={lowPass => patch({ lowPass })}/><Control label="低频 EQ" min={-12} max={12} step={.5} value={settings.eqLow} unit="dB" change={eqLow => patch({ eqLow })}/><Control label="中频 EQ" min={-12} max={12} step={.5} value={settings.eqMid} unit="dB" change={eqMid => patch({ eqMid })}/><Control label="高频 EQ" min={-12} max={12} step={.5} value={settings.eqHigh} unit="dB" change={eqHigh => patch({ eqHigh })}/><Control label="压缩器" min={0} max={100} step={1} value={settings.compressor} unit="%" change={compressor => patch({ compressor })}/><Control label="噪声门阈值" min={-80} max={-20} step={1} value={settings.gate} unit="dB" change={gate => patch({ gate })}/><Control label="齿音削减" min={0} max={100} step={1} value={settings.deEsser} unit="%" change={deEsser => patch({ deEsser })}/><Control label="混响" min={0} max={100} step={1} value={settings.reverb} unit="%" change={reverb => patch({ reverb })}/><Control label="延迟" min={0} max={100} step={1} value={settings.delay} unit="%" change={delay => patch({ delay })}/><label className="effect-switch"><input type="checkbox" checked={settings.limiter} onChange={event => patch({ limiter: event.target.checked })}/>片段/音轨限幅器</label></div><button className="reset-effects" onClick={() => onChange(defaultAudioEffects())}><RotateCcw/>恢复默认效果</button></section>
}
