import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './mobile.css'
import './transcript.css'
import './lyrics.css'
import './media-track.css'
import './mixer.css'
import './dynamic-tracks.css'
import './timeline-layout.css'
import './advanced-track-controls.css'
import './recording-stream.css'
import './effects-controls.css'

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
