import { Flag, MapPin, Trash2 } from 'lucide-react'
import type { TimelineMarker } from './project-storage'
import { formatTime } from './audio'

type Props = { markers: TimelineMarker[]; currentTime: number; selection: [number, number]; onAddPoint: () => void; onAddRegion: () => void; onChange: (id: string, patch: Partial<TimelineMarker>) => void; onDelete: (id: string) => void; onSeek: (time: number) => void }
const colors = ['#ffd15c', '#ff705a', '#63ddd6', '#75a7ff', '#d58cff']
export default function MarkerPanel({ markers, currentTime, selection, onAddPoint, onAddRegion, onChange, onDelete, onSeek }: Props) {
  return <section className="marker-panel"><div className="marker-heading"><strong>标记</strong><span>{markers.length}</span></div><div className="marker-add"><button onClick={onAddPoint}><MapPin/>在 {formatTime(currentTime, true)} 添加</button><button onClick={onAddRegion} disabled={selection[1] - selection[0] < .01}><Flag/>标记当前选区</button></div><div className="marker-list">{markers.sort((a, b) => a.time - b.time).map((marker, index) => <div className="marker-row" key={marker.id}><button className="marker-jump" style={{ background: marker.color }} title="跳转到标记" onClick={() => onSeek(marker.time)}>{index + 1}</button><div><input className="marker-name" value={marker.name} onChange={event => onChange(marker.id, { name: event.target.value })}/><div className="marker-times"><input type="number" min="0" step="0.01" value={marker.time.toFixed(2)} onChange={event => onChange(marker.id, { time: Math.max(0, Number(event.target.value) || 0) })}/>{marker.end !== undefined && <><span>—</span><input type="number" min={marker.time} step="0.01" value={marker.end.toFixed(2)} onChange={event => onChange(marker.id, { end: Math.max(marker.time, Number(event.target.value) || marker.time) })}/></>}</div></div><select aria-label="标记颜色" value={marker.color} onChange={event => onChange(marker.id, { color: event.target.value })}>{colors.map(color => <option key={color} value={color} style={{ color }}>{color}</option>)}</select><button className="marker-delete" aria-label="删除标记" onClick={() => onDelete(marker.id)}><Trash2/></button></div>)}</div></section>
}
